import { Settings } from './settings-types';

export const DEFAULT_SETTINGS: Settings = {
  general: {
    workspace_name: 'AMTME Studio OS',
    project_name: 'A Mí Tampoco Me Explicaron',
    creator_name: 'Christian Villamar',
    timezone: 'America/Cancun',
    language: 'es-419',
    date_format: 'DD/MM/YYYY',
    time_format: '24h',
    currency: 'MXN',
    week_start_day: 'Monday',
    editorial_preferred_day: 'Thursday',
    editorial_preferred_time_window: '09:00-11:00',
    system_status: 'active',
  },
  brand: {
    brand_name: 'AMTME',
    full_brand_name: 'A Mí Tampoco Me Explicaron',
    tagline: 'Lo que pensamos, lo que sentimos, lo que nadie nos explicó.',
    short_description:
      'Podcast de conversaciones profundas sobre vida, tecnología, emociones y filosofía.',
    voice_tone: 'Íntimo, directo, simbólico, humano, claro, vulnerable sin victimismo.',
    brand_keywords: [
      'conversación profunda',
      'filosofía',
      'tecnología',
      'emociones',
      'autenticidad',
    ],
    banned_words: ['básico', 'simple', 'fácil', 'trivial'],
    primary_palette: {
      yellow: '#FEE94B',
      navy: '#0C1F36',
      red: '#E0211E',
      white: '#F8F8F6',
    },
    typography: {
      primary_font: 'Inter',
      secondary_font: 'Playfair Display',
    },
    visual_rules: [
      'Alto contraste entre elementos',
      'Uso frecuente de espacio en blanco',
      'Tipografía clara y legible',
    ],
    thumbnail_rules: [
      'Incluir rostro o expresión emocional',
      'Colores primarios en fondo',
      'Texto corto y impactante',
    ],
  },
  podcast: {
    podcast_name: 'A Mí Tampoco Me Explicaron',
    host_name: 'Christian Villamar',
    main_platform: 'Spotify',
    secondary_platforms: ['Apple Podcasts', 'YouTube', 'Google Podcasts'],
    ideal_episode_duration_minutes: 75,
    max_episode_duration_minutes: 120,
    default_primary_cta: 'Escúchanos en Spotify',
    default_secondary_cta: 'Síguenos en redes sociales',
    official_episode_structure: [
      'Intro y bienvenida (2-3 min)',
      'Contexto del tema (5-10 min)',
      'Conversación principal (50-80 min)',
      'Reflexiones finales (5-10 min)',
      'Despedida y CTAs (2-3 min)',
    ],
    title_formula: '[Tema/Invitado] - AMTME Podcast #[Número]',
    editorial_categories: ['Filosofía', 'Tecnología', 'Negocios', 'Mentalidad', 'Relaciones'],
  },
  content: {
    active_formats: ['video_clip', 'quote_graphic', 'short_copy', 'transcript'],
    active_platforms: ['TikTok', 'Instagram Reels', 'YouTube Shorts', 'LinkedIn'],
    clips_per_episode: 5,
    quotes_per_episode: 3,
    copies_per_episode: 2,
    default_copy_style: 'Provocador y reflexivo',
    content_rules: [
      'No clickbait',
      'Mantener autenticidad de la conversación',
      'Incluir contexto de fuente',
      'Respetar derechos de autores/invitados',
    ],
    platform_specific_rules: {
      TikTok: ['Máx 60 segundos', 'Hook en primeros 3 segundos', 'Subtítulos siempre'],
      Instagram: ['Máx 90 segundos', 'Vertical 9:16', 'Hashtags relevantes'],
      YouTube: ['Mín 60 segundos', 'Miniatura con marca AMTME', 'Descripción con links'],
    },
    repurposing_rules: [
      'Video → Podcast (audio extract)',
      'Podcast → Blog (transcripción + análisis)',
      'Conversación → Social media clips',
    ],
    approval_required: true,
  },
  ai: {
    active_provider: 'claude',
    default_model: 'claude-opus-4-8',
    creative_temperature: 0.7,
    technical_temperature: 0.3,
    metrics_temperature: 0.2,
    max_tokens: 2048,
    generation_modes: ['creative', 'technical', 'analytical'],
    base_amtme_prompt:
      'Eres un experto en crear contenido para podcasts sobre filosofía, tecnología y emociones. Tu tono es íntimo, directo y auténtico.',
    enabled_modules: ['ia', 'contenido', 'metricas', 'guiones', 'creador-visual'],
    save_generation_history: true,
    allow_auto_overwrite: false,
    require_human_review: true,
  },
  metrics: {
    primary_metrics_platform: 'Spotify for Podcasters',
    accepted_file_types: ['csv', 'json', 'xlsx', 'pdf'],
    import_mode: 'Manual',
    strict_validation: true,
    allow_partially_valid_files: false,
    save_source_file: true,
    primary_kpis: ['listeners', 'completion_rate', 'engagement_rate', 'growth'],
    current_goals: {
      monthly_listeners: 50000,
      completion_rate: 0.85,
      follower_growth: 0.15,
    },
  },
  integrations: {
    spotify: {
      enabled: true,
      status: 'connected',
      last_sync_at: new Date().toISOString(),
    },
    youtube: {
      enabled: true,
      status: 'connected',
    },
    instagram: {
      enabled: true,
      status: 'requires_configuration',
    },
    tiktok: {
      enabled: true,
      status: 'requires_configuration',
    },
    linkedin: {
      enabled: true,
      status: 'disconnected',
    },
  },
  automation: {
    automation_enabled: true,
    execution_mode: 'requires_confirmation',
    active_automations: ['clip_generation', 'episode_publishing', 'social_posting'],
    analysis_frequency: 'weekly',
    weekly_report_day: 'Monday',
    weekly_report_time: '09:00',
    destructive_actions_require_confirmation: true,
  },
  notifications: {
    notify_pending_episodes: true,
    notify_missing_metrics: true,
    notify_performance_drop: true,
    notify_ready_to_publish: true,
    notify_overdue_tasks: true,
    notify_integration_errors: true,
    notify_weekly_recommendations: true,
    notification_channels: ['email', 'in_app'],
    priority_rules: {
      high: 'urgent_deadlines,technical_errors',
      medium: 'performance_metrics,social_engagement',
      low: 'weekly_summary,tips',
    },
  },
  security: {
    primary_user: 'Christian Villamar',
    email: 'christian@amtme.com',
    role: 'owner',
    session_status: 'active',
    last_access: new Date().toISOString(),
    two_factor_status: false,
    activity_log_enabled: true,
    module_permissions: {
      ia: ['owner', 'admin', 'editor'],
      metrics: ['owner', 'admin'],
      contenido: ['owner', 'admin', 'editor'],
      'creador-visual': ['owner', 'admin', 'editor'],
      guiones: ['owner', 'admin', 'editor'],
    },
  },
  data: {
    backup_status: 'ready',
    estimated_data_size: '2.5GB',
    logs_retention_days: 90,
    export_formats: ['json', 'csv', 'xlsx', 'pdf'],
  },
  system: {
    app_version: '0.1.0',
    environment: 'development',
    supabase_status: 'connected',
    vercel_status: 'connected',
    tests_status: 'passing',
    integrations_status: {
      spotify: true,
      youtube: true,
      analytics: true,
    },
  },
};
