'use client';
import React from 'react';
import type { SiteSection } from '@/lib/cms/types';
interface Props { sections: SiteSection[]; selectedKey: string | null; }
export function EditorPreview({ sections, selectedKey }: Props) {
  const get = (key: string) => { const s = sections.find((x) => x.section_key === key); return s?.is_visible !== false ? s?.content as Record<string, unknown> | undefined : undefined; };
  const hl = (key: string): React.CSSProperties => selectedKey === key ? { outline: '2px solid #FEE94B', outlineOffset: 2 } : {};
  const hero = get('hero'), featured = get('featured_episode'), about = get('about'), manifesto = get('manifesto'), christian = get('about_christian'), newsletter = get('newsletter'), footer = get('footer');
  return (
    <div style={{ fontFamily: 'Georgia, serif', color: '#0C1F36', background: '#F5F2EA', minHeight: '100vh' }}>
      {hero && <section style={{ background: '#0C1F36', color: '#fff', padding: '80px 48px', ...hl('hero') }}><p style={{ fontSize: 10, letterSpacing: '0.15em', color: '#FEE94B', margin: '0 0 24px' }}>{hero.eyebrow as string}</p><h1 style={{ fontSize: 38, fontWeight: 700, maxWidth: 700, margin: '0 0 24px', lineHeight: 1.2 }}>{hero.title as string}</h1><p style={{ fontSize: 16, color: 'rgba(255,255,255,0.75)', maxWidth: 600, margin: '0 0 32px', lineHeight: 1.7 }}>{hero.subtitle as string}</p></section>}
      {featured && <section style={{ padding: '64px 48px', ...hl('featured_episode') }}><p style={{ fontSize: 10, letterSpacing: '0.15em', color: '#E0211E', margin: '0 0 8px' }}>{featured.eyebrow as string}</p><h2 style={{ fontSize: 28, fontWeight: 700, margin: '0 0 16px' }}>{featured.episode_title as string}</h2><p style={{ fontSize: 15, lineHeight: 1.7, color: 'rgba(12,31,54,0.7)', maxWidth: 600, margin: 0 }}>{featured.episode_description as string}</p></section>}
      {about && <section style={{ padding: '64px 48px', background: '#0C1F36', color: '#fff', ...hl('about') }}><p style={{ fontSize: 10, letterSpacing: '0.15em', color: '#FEE94B', margin: '0 0 16px' }}>{about.eyebrow as string}</p><h2 style={{ fontSize: 30, fontWeight: 700, margin: '0 0 24px' }}>{about.headline as string}</h2><p style={{ fontSize: 15, lineHeight: 1.8, color: 'rgba(255,255,255,0.75)', maxWidth: 700, margin: 0 }}>{about.body as string}</p></section>}
      {manifesto && <section style={{ padding: '80px 48px', background: '#FEE94B', ...hl('manifesto') }}><blockquote style={{ fontSize: 26, fontStyle: 'italic', margin: 0, maxWidth: 600 }}><p style={{ margin: '0 0 4px' }}>{manifesto.quote_line1 as string}</p><p style={{ margin: '0 0 4px' }}>{manifesto.quote_line2 as string}</p><p style={{ margin: 0 }}>{manifesto.quote_line3 as string}</p></blockquote></section>}
      {christian && <section style={{ padding: '64px 48px', ...hl('about_christian') }}><p style={{ fontSize: 10, letterSpacing: '0.15em', color: '#E0211E', margin: '0 0 16px' }}>{christian.eyebrow as string}</p><h2 style={{ fontSize: 26, fontWeight: 700, margin: '0 0 20px' }}>{christian.headline as string}</h2><p style={{ fontSize: 15, lineHeight: 1.8, color: 'rgba(12,31,54,0.75)', maxWidth: 600, margin: '0 0 12px' }}>{christian.body1 as string}</p><p style={{ fontSize: 15, lineHeight: 1.8, color: 'rgba(12,31,54,0.75)', maxWidth: 600, margin: 0 }}>{christian.body2 as string}</p></section>}
      {newsletter && <section style={{ padding: '64px 48px', background: '#FEE94B', ...hl('newsletter') }}><p style={{ fontSize: 10, letterSpacing: '0.15em', margin: '0 0 16px' }}>{newsletter.eyebrow as string}</p><h2 style={{ fontSize: 26, fontWeight: 700, margin: '0 0 16px' }}>{newsletter.headline as string}</h2><p style={{ fontSize: 15, lineHeight: 1.7, margin: '0 0 24px' }}>{newsletter.body as string}</p><button style={{ background: '#0C1F36', color: '#fff', padding: '12px 24px', borderRadius: 6, border: 'none', fontSize: 14, fontWeight: 600 }}>{newsletter.cta_label as string}</button></section>}
      {footer && <footer style={{ background: '#0C1F36', color: '#fff', padding: '48px', ...hl('footer') }}><p style={{ fontWeight: 700, fontSize: 16, margin: '0 0 8px' }}>{footer.brand_name as string}</p><p style={{ fontSize: 13, color: 'rgba(255,255,255,0.5)', margin: '0 0 32px' }}>{footer.tagline as string}</p><p style={{ fontSize: 12, color: 'rgba(255,255,255,0.3)', margin: 0 }}>{footer.copyright as string}</p></footer>}
    </div>
  );
}
